# Generated by Django 5.2.7 on 2025-10-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mangaka'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfo',
            name='Big3',
            field=models.TextField(default='N/A'),
        ),
    ]
