# Generated by Django 5.2.7 on 2025-10-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_animeinfo_big3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='Big3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
