# Generated by Django 5.2.7 on 2025-10-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_animeinfo_big3'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
