# Generated by Django 5.2.7 on 2025-10-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_censorinfo_animeinfo_censor_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeinfo',
            name='censor_details',
        ),
        migrations.DeleteModel(
            name='CensorInfo',
        ),
    ]
