# Generated by Django 5.2.7 on 2025-10-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_censorinfo_animeinfo_censor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfo',
            name='mangaka_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_stories', to='home.mangaka'),
        ),
    ]
