# Generated by Django 5.2.7 on 2025-10-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_animeinfo_mangaka_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='animeinfo',
            name='studio',
            field=models.ManyToManyField(related_name='animated_by', to='home.studio'),
        ),
    ]
