# Generated by Django 5.2.7 on 2025-10-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_studio_animeinfo_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeinfo',
            old_name='mangaka_of',
            new_name='manga_of',
        ),
    ]
