# Generated by Django 5.2.7 on 2025-11-02 04:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_animeinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
